[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# Visual {{{
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'rhysd/wallaby.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
# }}}

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Unite {{{
[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'
# }}}

# Syntacs Checker
[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-shart-with-echo)
'''

[[plugins]]
repo = 'kana/vim-operator-user'
