# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
${directory}${custom.arch}${git_branch}${git_status}${gcloud}${jobs}
${character}\\$ """

add_newline = false

[character]
success_symbol = '[:\)](bold green)'
error_symbol = '[:\(](bold red)'

[cmd_duration]
format = '[$duration](italic 75)'

[directory]
style = '115'

[gcloud]
format = 'on [$symbol$active]($style) '
style = '75'

[git_branch]
style = '115'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = '75'
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = '✓'
untracked = ''
stashed = ''
modified = '[+](red)'
staged = ''
renamed = ''
deleted = ''

[memory_usage]
disabled = false

[jobs]
format = '[\($number\)]($style) '
number_threshold = 1
style = 'red'

[custom.arch]
command = "uname -m"
format = '($output)'
